// Generated by scripts/sync-web-contracts.mjs; do not edit by hand.
// Source SHA-256: e26ec76e25fc696162f7037cd2051b79bd0fe6574095a1afcb42ae7d0fd178bf
import { z } from "zod";

// Browser-safe: keep this module free of filesystem, database and model runtime imports.
export const GENERAL_ATTACHMENT_LIMIT = 8;
export const GENERAL_ATTACHMENT_MAX_BYTES = 80 * 1024 * 1024;
export const IdSchema = z.string().trim().min(1).max(256);
export const RevisionSchema = z.number().int().positive();
export const ModelRefSchema = z.object({ service: IdSchema, model: IdSchema }).strict();
export type ModelRef = z.infer<typeof ModelRefSchema>;

export const ResourceRefSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("attachment"), id: IdSchema, revision: RevisionSchema }).strict(),
  z.object({ kind: z.literal("artifact"), id: IdSchema, revision: RevisionSchema }).strict(),
]);
export type ResourceRef = z.infer<typeof ResourceRefSchema>;
export const MessagePartSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("text"), text: z.string().max(1_048_576) }).strict(),
  z.object({ type: z.literal("resource"), ref: ResourceRefSchema }).strict(),
]);
export type MessagePart = z.infer<typeof MessagePartSchema>;

export const AgentMessageInputSchema = z.object({
  messageId: IdSchema,
  sessionId: IdSchema,
  parts: z.array(MessagePartSchema).min(1).max(32),
  model: ModelRefSchema,
  selectedSkillAssetIds: z.array(IdSchema).max(64),
  selectedSkillVersions: z.record(z.string().regex(/^[1-9][0-9]{0,18}$/), RevisionSchema).optional(),
  selectedAgentAssetIds: z.array(IdSchema).max(64),
  capabilityRefs: z.array(z.object({ kind: IdSchema, id: IdSchema }).strict()).max(64),
  creationStrategy: z.enum(["fast", "simulate"]),
  creationMode: z.enum(["guided", "conversation", "film"]).optional(),
  officialPersonaId: z.string().regex(/^[a-z0-9][a-z0-9-]{0,63}$/).optional(),
}).strict().superRefine((message, ctx) => {
  for (const assetId of Object.keys(message.selectedSkillVersions ?? {})) {
    if (!message.selectedSkillAssetIds.includes(assetId)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["selectedSkillVersions", assetId], message: "A version must belong to an explicitly selected Skill" });
  }
  if (!message.parts.some(part => part.type === "resource" || part.text.trim().length > 0)) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["parts"], message: "Message needs text or a resource" });
  }
  if (message.parts.filter(part => part.type === "resource").length > GENERAL_ATTACHMENT_LIMIT) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["parts"], message: `At most ${GENERAL_ATTACHMENT_LIMIT} resources per message` });
  }
});
export type AgentMessageInput = z.infer<typeof AgentMessageInputSchema>;

/** Explicit choices win; automatic routing changes the persona, never the selected model or tools. */
export function inferGeneralPersona(input?: Pick<AgentMessageInput, "parts" | "capabilityRefs" | "officialPersonaId">): string {
  if (input?.officialPersonaId) return input.officialPersonaId;
  const text = input?.parts.flatMap(part => part.type === "text" ? [part.text] : []).join("\n") ?? "";
  if (/拆书|拆解.{0,8}(小说|书籍|这本书)|分析.{0,8}(开篇|伏笔)/u.test(text)) return "tianwang";
  if (/图片|图像|封面|截图|画一|绘画|生图|润色|文风|打磨文字/u.test(text)) return "tiangong";
  if (/推演|仿真|模拟.{0,8}(人物|角色|选择)/u.test(text)) return "tianyan";
  if (input?.capabilityRefs.some(ref => ref.kind === "source")) return "tianwang";
  if (/脑洞|灵感|故事|小说|写书|写作/u.test(text)) return "tianmo";
  return "zhushen";
}

const PromptReferencesSchema = z.array(z.object({
  kind: z.enum(["prompt-template", "prompt-template-once"]), id: IdSchema,
}).strict()).max(64);

export const NovelCreationIntentSchema = z.object({
  title: z.string().trim().min(1).max(120), genre: z.string().trim().min(1).max(120),
  instruction: z.string().trim().min(1).max(20000), platform: z.enum(["qidian", "tomato", "feilu", "other"]),
  language: z.enum(["zh", "en"]), targetChapters: z.number().int().min(1).max(2000),
  chapterWordCount: z.number().int().min(1000).max(10000), templateIds: z.array(IdSchema).max(16),
  strategy: z.enum(["fast", "simulate"]), model: ModelRefSchema,
  promptRefs: PromptReferencesSchema.optional(),
}).strict();
export type NovelCreationIntent = z.infer<typeof NovelCreationIntentSchema>;
export const GeneralQuestionActionSchema = z.object({
  kind: z.literal("novel_creation"), proposalId: IdSchema, digest: z.string().regex(/^[a-f0-9]{64}$/), intent: NovelCreationIntentSchema,
}).strict();
export type GeneralQuestionAction = z.infer<typeof GeneralQuestionActionSchema>;

export const RunStatusSchema = z.enum([
  "queued", "waiting_resources", "running", "waiting_user", "waiting_external",
  "cancelling", "succeeded", "failed", "cancelled", "interrupted",
]);
export type RunStatus = z.infer<typeof RunStatusSchema>;
export const ToolStatusSchema = z.enum(["prepared", "executing", "succeeded", "failed", "cancelled", "unknown"]);
export type ToolStatus = z.infer<typeof ToolStatusSchema>;
export const AttachmentStatusSchema = z.enum(["uploading", "stored", "parsing", "ready", "failed"]);
export type AttachmentStatus = z.infer<typeof AttachmentStatusSchema>;
export const GeneralAttachmentSchema = z.object({
  id: IdSchema, revision: RevisionSchema, filename: z.string(), mimeType: z.string(), byteLength: z.number().int().nonnegative(), status: AttachmentStatusSchema,
  kind: z.enum(["text", "image"]).optional(), charCount: z.number().int().nonnegative().optional(), encoding: z.string().optional(),
  ocrPages: z.array(z.number().int().positive()).optional(), ocrCompletedPages: z.array(z.number().int().positive()).optional(), ocrUncertainPages: z.array(z.number().int().positive()).optional(),
  error: z.object({ code: z.string(), message: z.string() }).strict().optional(),
}).strict();
export type GeneralAttachment = z.infer<typeof GeneralAttachmentSchema>;
export const GeneralSkillSummarySchema = z.object({
  assetId: IdSchema, id: IdSchema, title: z.string(), description: z.string(), version: RevisionSchema, creatorName: z.string(),
}).strict();
export type GeneralSkillSummary = z.infer<typeof GeneralSkillSummarySchema>;
export const SourceSpanSchema = z.object({
  attachmentId: IdSchema,
  revision: RevisionSchema,
  start: z.number().int().nonnegative(),
  end: z.number().int().nonnegative(),
  page: z.number().int().positive().optional(),
  chapterId: IdSchema.optional(),
}).strict().refine(span => span.end >= span.start, { path: ["end"], message: "End precedes start" });
export type SourceSpan = z.infer<typeof SourceSpanSchema>;
export const ArtifactKindSchema = z.enum(["report", "image", "code", "file", "skill"]);
export type ArtifactKind = z.infer<typeof ArtifactKindSchema>;
export const ArtifactRefSchema = z.object({
  id: IdSchema, revision: RevisionSchema, kind: ArtifactKindSchema, title: z.string().min(1).max(512),
}).strict();
export type ArtifactRef = z.infer<typeof ArtifactRefSchema>;
export const GeneralToolResultSchema = z.discriminatedUnion("status", [
  z.object({ status: z.literal("succeeded"), summary: z.string(), artifacts: z.array(ArtifactRefSchema), citations: z.array(SourceSpanSchema) }).strict(),
  z.object({ status: z.literal("running"), summary: z.string(), runId: IdSchema, workflowId: IdSchema.optional() }).strict(),
  z.object({ status: z.literal("waiting_user"), questionId: IdSchema, question: z.string().min(1), options: z.array(z.string()) }).strict(),
  z.object({ status: z.literal("failed"), code: IdSchema, message: z.string(), retryable: z.boolean() }).strict(),
  z.object({ status: z.literal("cancelled"), summary: z.string() }).strict(),
]);
export type GeneralToolResult = z.infer<typeof GeneralToolResultSchema>;

const EventBase = z.object({
  eventId: IdSchema, sessionId: IdSchema, runId: IdSchema,
  seq: z.number().int().positive(), createdAt: z.string().datetime({ offset: true }),
});
export const AgentDestinationSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("creation"), messageId: IdSchema, instruction: z.string().min(1).max(20000),
    mode: z.enum(["guided", "conversation", "film"]), promptRefs: PromptReferencesSchema.optional() }).strict(),
  z.object({ kind: z.literal("deconstruction"), sourceId: z.string().regex(/^[a-z0-9][a-z0-9._-]{0,127}$/) }).strict(),
]);
export type AgentDestination = z.infer<typeof AgentDestinationSchema>;

export const PublicEventSchema = z.discriminatedUnion("type", [
  EventBase.extend({ type: z.literal("message"), payload: z.object({
    messageId: IdSchema, role: z.enum(["user", "assistant"]), parts: z.array(MessagePartSchema),
    final: z.boolean().optional(),
  }).strict() }).strict(),
  EventBase.extend({ type: z.literal("status"), payload: z.object({
    status: RunStatusSchema, summary: z.string(),
    progress: z.object({ current: z.number().nonnegative(), total: z.number().positive(), label: z.string() }).strict()
      .refine(progress => progress.current <= progress.total).optional(),
  }).strict() }).strict(),
  EventBase.extend({ type: z.literal("tool"), payload: z.object({
    callId: IdSchema, name: IdSchema, label: z.string(), status: ToolStatusSchema,
    summary: z.string().optional(), artifacts: z.array(ArtifactRefSchema).optional(),
    destination: AgentDestinationSchema.optional(),
  }).strict() }).strict(),
  EventBase.extend({ type: z.literal("artifact"), payload: z.object({ artifact: ArtifactRefSchema }).strict() }).strict(),
  EventBase.extend({ type: z.literal("question"), payload: z.object({
    questionId: IdSchema, question: z.string().min(1), options: z.array(z.string()), revision: RevisionSchema,
    action: GeneralQuestionActionSchema.optional(),
  }).strict() }).strict(),
  EventBase.extend({ type: z.literal("input_applied"), payload: z.object({
    messageId: IdSchema, appliedTo: z.enum(["current_turn", "next_task"]),
  }).strict() }).strict(),
]);
export type PublicEvent = z.infer<typeof PublicEventSchema>;
export type PublicEventData = PublicEvent extends infer E
  ? E extends PublicEvent ? Pick<E, "type" | "payload"> : never : never;

export const GeneralSessionSnapshotSchema = z.object({
  sessionId: IdSchema, sessionKind: z.literal("general"), cursor: z.number().int().nonnegative(),
  messages: z.array(z.object({ state: z.enum(["pending", "applied", "cancelled"]) }).passthrough().transform((value, ctx) => {
    const { state, ...input } = value;
    const parsed = AgentMessageInputSchema.safeParse(input);
    if (!parsed.success) { for (const issue of parsed.error.issues) ctx.addIssue(issue); return z.NEVER; }
    return { ...parsed.data, state };
  })),
  runs: z.array(z.object({ id: IdSchema, status: RunStatusSchema, summary: z.string(), revision: RevisionSchema, cancelRequested: z.boolean() }).strict()),
  events: z.array(PublicEventSchema), artifacts: z.array(ArtifactRefSchema), attachments: z.array(GeneralAttachmentSchema),
}).strict();
export type GeneralSessionSnapshot = z.infer<typeof GeneralSessionSnapshotSchema>;

export const LegacyAttachmentSchema = z.object({
  id: IdSchema, filename: z.string().min(1).max(512), mediaType: z.string().max(256), dataUrl: z.string().min(1),
}).strict();
export type LegacyAttachment = z.infer<typeof LegacyAttachmentSchema>;

export const TERMINAL_RUN_STATUSES: ReadonlySet<RunStatus> = new Set(["succeeded", "failed", "cancelled", "interrupted"]);
