import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createApplication } from './app.mjs';
import { selectedContext } from './context.mjs';
import { cloudCatalog } from './cloud-catalog.mjs';
import { freeAccess } from './free-access.mjs';

test('Free onboarding validates the upstream owner/group/status and gates real catalogs without granting membership', async t => {
  const calls = []; let active = true, reachable = true, accountId = '42';
  const free = { id: 7, user_id: 42, key: 'fixture-free-secret', name: 'My Free', status: 'active', group_id: 2, group: { id: 2, name: 'openskoob-free', status: 'active', rate_multiplier: 0 }, expires_at: null };
  const upstream = createServer(async (req, res) => {
    let raw = ''; for await (const part of req) raw += part;
    calls.push({ path: req.url, auth: req.headers.authorization, user: req.headers['x-skoob-user'], method: req.method });
    const reply = (data, status = 200) => { res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data)); };
    if (!reachable) return reply({ message: 'Unavailable' }, 503);
    if (req.url === '/api/v1/account/verify-key') return reply({ ok: true, user: { id: 42 } });
    if (req.url === '/api/v1/account/status') return req.headers['x-skoob-user'] === accountId ? reply({ loggedIn: true, user: { id: accountId }, sub2apiUrl: base }) : reply({ loggedIn: false });
    if (req.url === '/api/v1/account/membership') return reply({ loggedIn: true, isMember: false, entitlements: [], plan: null });
    const key = { ...free, status: active ? 'active' : 'disabled' };
    if (req.url.startsWith('/api/v1/keys?')) return reply({ code: 0, data: { items: [key, { ...key, id: 8, group: { ...key.group, name: 'paid' } }], total: 2 } });
    if (req.url === '/api/v1/keys/7') return reply({ code: 0, data: key });
    if (req.url === '/api/v1/keys/8') return reply({ code: 0, data: { ...key, id: 8, group: { ...key.group, name: 'paid' } } });
    if (req.url === '/api/v1/keys/9') return reply({ code: 0, data: { ...key, id: 9, user_id: 99 } });
    if (req.url === '/api/v1/keys/10') return reply({ code: 0, data: { ...key, id: 10, expires_at: '2020-01-01T00:00:00Z' } });
    if (req.url === '/api/v1/genres') return reply({ genres: [{ id: 'same', name: 'Official genre' }] });
    if (req.url === '/api/v1/genres/same/cluster') return reply({ profile: { name: 'Official genre' }, body: 'official writing guidance', books: [], agents: [] });
    if (req.url === '/api/v1/agent-templates') return reply({ templates: [{ id: 'same', name: 'Official template', content: 'public character' }] });
    if (req.url === '/api/v1/agent-prototypes') return reply({ prototypes: [{ id: 'same', name: 'Public character', tags: [] }] });
    if (req.url === '/api/v1/skills') return reply({ skills: [{ id: 'same', name: 'Public skill', body: 'public guidance' }] });
    if (req.url.startsWith('/api/v1/tianmo/brainstorm/cards')) return reply({ cards: [{ id: 'card', title: 'Real upstream inspiration' }] });
    if (req.url === '/api/v1/tianmo/inspiration/plan') return reply({ error: { code: 'MEMBERSHIP_REQUIRED', message: '此功能需要对应会员权益' } }, 403);
    return reply({ error: 'NOT_FOUND' }, 404);
  });
  await new Promise(r => upstream.listen(0, '127.0.0.1', r)); const base = `http://127.0.0.1:${upstream.address().port}`;
  t.after(() => new Promise(r => upstream.close(r)));
  const realFetch = globalThis.fetch;
  t.mock.method(globalThis, 'fetch', (url, init) => String(url) === 'https://lai.gaotk.com/v1/models' ? Promise.resolve(Response.json({ data: [{ id: 'free-model' }] })) : realFetch(url, init));
  const dir = mkdtempSync(join(tmpdir(), 'skoob-free-test-')); let instance = createApplication({ dataDir: dir, cloudEnv: {} });
  t.after(async () => { await instance.close(); rmSync(dir, { recursive: true, force: true }); });
  const login = await (await instance.app.request('/api/v1/local/session', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Skoob-Local': '1' }, body: JSON.stringify({}) })).json();
  const request = (path, method = 'GET', body) => instance.app.request('/api/v1' + path, { method, headers: { 'Content-Type': 'application/json', 'X-Skoob-Local': '1', Authorization: `Bearer ${login.token}` }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const json = async (path, method, body) => { const r = await request(path, method, body); const data = await r.json(); assert.ok(r.ok, JSON.stringify(data)); return data; };
  assert.equal((await json('/local/cloud/access')).ready, false);
  for (const path of ['/tianmo/brainstorm/cards', '/tianmo/brainstorm/cards/card/image', '/tianmo/hotboard/boards', '/tianmo/hotboard/aggregate', '/tianmo/scan/platforms', '/tianwang/catalog', '/tianwang-library/templates', '/covers/file/asset/1']) assert.equal((await request(path)).status, 403, path); assert.equal(calls.length, 0);
  await json('/local/onboarding', 'PUT', { choice: 'local' }); assert.equal((await json('/local/onboarding')).choice, 'local');
  await json('/genres', 'POST', { id: 'same', name: 'Local genre' });
  await json('/services/config', 'PUT', { services: [{ service: 'custom', name: 'My model', baseUrl: base }], service: 'custom:My model', defaultModel: 'my-model' });
  await json('/services/custom%3AMy%20model/secret', 'PUT', { apiKey: 'my-own-secret' });
  await json('/local/cloud', 'PUT', { baseUrl: base, apiKey: 'official-token' });
  assert.equal((await json('/local/cloud/access')).ready, false); assert.equal((await request('/tianmo/brainstorm/cards')).status, 403);
  const listed = await json('/local/cloud/keys'); assert.equal(listed.keys[0].eligible, true); assert.equal(listed.keys[1].eligible, false); assert.ok(!JSON.stringify(listed).includes(free.key));
  for (const keyId of ['8', '9', '10', '../7']) assert.ok((await request('/local/cloud/keys/select', 'POST', { keyId })).status >= 400);
  const selected = await json('/local/cloud/keys/select', 'POST', { keyId: '7' });
  assert.equal((await json('/local/cloud/access')).ready, true); assert.equal((await json('/account/membership')).isMember, false);
  assert.equal((await json('/services/config')).service, 'custom:My model'); assert.equal(instance.store.secret('custom:My model'), 'my-own-secret');
  assert.ok(!JSON.stringify(instance.store.list('secrets')).includes(free.key));
  const genres = (await json('/genres')).genres; assert.deepEqual(genres.map(g => g.id), ['same', 'official:same']); assert.equal(genres[1].editable, false);
  assert.equal((await json('/agent-templates')).templates[0].id, 'official:same');
  assert.equal((await json('/agent-prototypes')).prototypes[0].id, 'official:same');
  assert.equal((await json('/tianmo/brainstorm/cards')).cards[0].id, 'card');
  assert.equal((await request('/tianmo/inspiration/plan', 'POST', {})).status, 403);
  assert.equal((await request('/genres/official%3Asame', 'DELETE')).status, 403); assert.equal(instance.store.get('genres', 'same').name, 'Local genre');
  const catalog = cloudCatalog(instance.store, {}, freeAccess(instance.store, {}));
  assert.match(await selectedContext(instance.store, { capabilityRefs: [{ kind: 'genre', id: 'official:same' }] }, catalog.material), /official writing guidance/);
  assert.ok(calls.filter(c => c.path === '/api/v1/genres').every(c => !c.auth));
  assert.ok(!calls.some(c => c.auth === `Bearer ${login.token}`)); assert.ok(!calls.some(c => c.path.startsWith('/api/v1/keys') && c.method !== 'GET'));
  await instance.close(); instance = createApplication({ dataDir: dir, cloudEnv: {} }); assert.equal((await json('/local/cloud/access')).ready, true);
  active = false;
  assert.equal((await request('/tianmo/brainstorm/cards')).status, 200); // short, previously verified snapshot
  const realNow = Date.now; t.mock.method(Date, 'now', () => realNow() + 31000);
  assert.equal((await request('/tianmo/brainstorm/cards')).status, 403); Date.now.mock.restore();
  assert.equal((await json('/local/cloud/access?refresh=1')).ready, false); assert.equal((await request('/tianmo/brainstorm/cards')).status, 403); assert.equal((await json('/genres')).genres.length, 1);
  active = true; reachable = false; assert.equal((await json('/local/cloud/access?refresh=1')).ready, false); reachable = true;
  await json('/services/' + encodeURIComponent(selected.service), 'DELETE'); assert.equal((await json('/local/cloud/access')).ready, false);
  assert.equal(instance.store.secret(selected.service), ''); assert.equal((await json('/local/cloud/access')).ready, false);
  await json('/local/cloud/keys/select', 'POST', { keyId: '7' }); accountId = '99'; assert.equal((await json('/local/cloud/access?refresh=1')).ready, false); accountId = '42';
  await json('/local/cloud', 'PUT', { baseUrl: base, apiKey: '' }); assert.equal((await json('/local/cloud/access')).ready, false); assert.equal((await json('/genres')).genres.length, 1);
  assert.equal(instance.store.secret('custom:My model'), 'my-own-secret');
});

test('pasted official Key connects without account login and never becomes a platform identity', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'skoob-direct-key-test-'));
  let instance = createApplication({ dataDir: dir, cloudEnv: {} });
  t.after(async () => { await instance.close(); rmSync(dir, { recursive: true, force: true }); });
  // Old installations with a password record also bootstrap with no password.
  instance.store.set('settings', 'auth', { salt: 'old', digest: 'old' });
  await instance.close(); instance = createApplication({ dataDir: dir, cloudEnv: {} });
  const boot = await instance.app.request('/api/v1/local/session', { method: 'POST', headers: { 'X-Skoob-Local': '1' } });
  assert.equal(boot.status, 200); const session = await boot.json();
  const request = (path, method = 'GET', body) => instance.app.request('/api/v1' + path, { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.token}` }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const json = async (...args) => { const r = await request(...args); const data = await r.json(); assert.ok(r.ok, JSON.stringify(data)); return data; };
  let revoked = false; const calls = [];
  t.mock.method(globalThis, 'fetch', async (url, init) => {
    const path = String(url); const auth = new Headers(init.headers).get('authorization'); calls.push({ path, auth });
    if (path.startsWith('https://lai.gaotk.com/')) {
      if (auth === 'Bearer invalid' || revoked) return Response.json({ error: 'INVALID_KEY' }, { status: 401 });
      if (path.endsWith('/sub2api/billing')) return Response.json({ object: 'sub2api.key_billing', schema_version: 1, billing_scope: 'token', effective_rate_multiplier: 0 });
      if (path.endsWith('/models')) return auth === 'Bearer expired' ? Response.json({ error: 'API_KEY_EXPIRED' }, { status: 403 }) : Response.json({ data: [{ id: 'free-model' }] });
    }
    assert.equal(auth, null, 'model/local credentials must never enter public catalog requests');
    if (path === 'https://skoob.cc/api/v1/genres') return Response.json({ genres: [{ id: 'official-genre', name: '官方流派' }] });
    if (path === 'https://skoob.cc/api/v1/tianmo/brainstorm/cards') return Response.json({ cards: [{ id: 'official-card' }] });
    throw new Error('unexpected upstream request');
  });
  assert.equal((await request('/tianmo/brainstorm/cards')).status, 403);
  await json('/local/onboarding', 'PUT', { choice: 'local' });
  assert.deepEqual((await json('/genres')).genres, []); assert.equal(calls.length, 0);
  await json('/services/config', 'PUT', { service: 'custom:mine', defaultModel: 'mine', services: [{ service: 'custom', name: 'mine' }] });
  for (const apiKey of ['', 'invalid', 'expired']) assert.ok((await request('/local/cloud/key', 'POST', { apiKey })).status >= 400);
  assert.equal((await json('/local/cloud/access')).ready, false);
  const connected = await json('/local/cloud/key', 'POST', { apiKey: 'valid-free-model-key' });
  assert.equal((await json('/local/cloud/access')).ready, true);
  assert.equal((await json('/local/onboarding')).choice, 'official');
  assert.equal((await json('/local/cloud')).configured, false);
  assert.equal((await json('/account/membership')).isMember, false);
  assert.equal((await json('/services/config')).service, 'custom:mine');
  assert.equal((await json('/tianmo/brainstorm/cards')).cards[0].id, 'official-card');
  assert.equal((await json('/genres')).genres[0].source, 'official');
  assert.equal((await request('/tianmo/inspiration/plan', 'POST', {})).status, 503);
  instance.store.set('agentTemplates', 'mine', { id: 'mine', name: 'My template', content: 'Own content' });
  assert.equal((await request('/local/cloud/templates/agent/mine/upload', 'POST', {})).status, 503);
  assert.ok(!JSON.stringify(instance.store.list('secrets')).includes('valid-free-model-key'));
  assert.ok(!JSON.stringify(await json('/local/cloud/access')).includes('valid-free-model-key'));
  await instance.close(); instance = createApplication({ dataDir: dir, cloudEnv: {} });
  assert.equal((await json('/local/cloud/access')).ready, true);
  revoked = true; assert.equal((await json('/local/cloud/access?refresh=1')).ready, false);
  assert.equal((await request('/tianmo/brainstorm/cards')).status, 403);
  revoked = false; await json('/local/cloud/key', 'POST', { apiKey: 'valid-free-model-key' });
  await json('/local/cloud/key', 'DELETE'); assert.equal((await json('/local/cloud/access')).ready, false);
  assert.equal(instance.store.secret(connected.service), 'valid-free-model-key');
  assert.equal((await json('/services/config')).service, 'custom:mine');
});
