import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { App } from "./App";
import { SelfHost } from "./SelfHost";
import { I18nProvider } from "./i18n/index";
import "./styles/tokens.css";
import "./styles/global.css";
import "./styles/pages.css";
createRoot(document.getElementById("root")!).render(<StrictMode><I18nProvider><BrowserRouter><SelfHost><App /></SelfHost></BrowserRouter></I18nProvider></StrictMode>);
